### ISSUE TITLE
Convert repository structure image to markdown

### ISSUE THREAD

**Issue by jmshapir** [jmshapir/TestWorkflow#2]
@francescomariaesposito here is an initial issue to get us used to github workflow.

At [this location](https://github.com/jmshapir/TestWorkflow/wiki/Repository-Structure) I have posted a sketch of how I plan to organize the repository. It is in image format.

Can you please use markdown to replace the image with a markdown table?

**Comment by francescomariaesposito** [comment]
@jmshapir I have some doubts on the way I need to proceed here.
1. Could you please explain me what is the advantage of writing tables with Markdown instead of using latex code? I think latex is easier and more straightforward. Isn't it? I am asking since this is the first time I use Markdown and since this table is really a basic one (it may be that for more complex tables Markdown works better).
2. Could you also double check the table (or code) and see if this is what you were looking for? Is it possible that the output and the code of the table when we use Markdown are the same thing? For simplicity, I attach a txt file with the table here: [table_repository_structure.txt](https://github.com/jmshapir/TestWorkflow/files/386997/table_repository_structure.txt)
3. Where should I copy or import this code (or output table) in Github? Do you want me to copy the code here in a comment to this issue? Or should I copy the code in Wiki/Repository Structure/New Page ? (basically [here](https://github.com/jmshapir/TestWorkflow/wiki/_new))
4. Please notice that I have used [this website](http://www.tablesgenerator.com/markdown_tables) to create the table in Markdown format (basically by hand). Is it the right way to do it? Or there is a fastest way?
5. If the code of the table, as attached, is ok for you, please tell me if you want me to follow the following procedure now:
   
      a. Clone your entire repository to my local pc using the usual one line code in my windows command prompt (even if all data for the moment refers to the ethnicity project and not to the protest project)
   b. Create a branch called task#2_create_table_repository_structure on Github
   c. Upload the code of the table in my new branch and then send you a pull request (if I understood correctly a pull request is needed to show the other participants the work I have done and let them comment on that)
   d. Then, after your comments, should I compile and update the master brunch? Or (I think this is more appropriate) I should follow one of the possibilities I described above in 3? 
   e. Finally should I delete the created branch (if I need to create it before) and/or close the Issue?

Did I forget to do something else here?

**Comment by jmshapir** [comment]
1. I don't see any advantage relative to LaTex, but the git Wiki is designed to work with markdown.
2. I think we had a misunderstanding. All I wanted was for you to edit the Wiki page I posted so that instead of an image file it has a markdown table.
3. You can just edit the Wiki page via the web browser.
4. That's fine, or you can just write the pipes | in yourself. I have found that isn't too burdensome.
5. For this issue, you won't need to interact with the repo except via the web browser. Eventually when you need to interact with the repo you will definitely need to clone it. Incidentally, the Github desktop client is pretty helpful, although of course you can do everything you need via command line.

**Comment by francescomariaesposito** [comment]
@jmshapir ok thanks. I did it. It was much easier than what I was thinking.
